sudo: required
services:
  - docker

before_install:
  - docker build -t zezenk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zezenk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucker_name: "elasticbeanstalk-ap-southeast-1-498093216196"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY